version: "3"

services:
    app:
        container_name: node_app
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run dev
        depends_on:
            - db
        volumes:
            - .:/usr/src/app
        ports:
            - "8080:8080"
        expose:
            - "8080"
        links:
            - db
        networks:
            - cnc-network
        environment:
            WAIT_HOSTS: mysql:3306
        # command: ["./wait-for-db.sh"]

    db:
        container_name: cnc_db
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USERNAME}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - type=bind
            - source=./docker/db
            - target=/docker-entrypoint-initdb.d
        expose:
            - "3306"
        networks:
            - cnc-network

networks:
  cnc-network:
    driver: bridge
