CREATE USER "loudjein"@"%" IDENTIFIED BY 'secret1234';

CREATE SCHEMA
`cnc_iiot` DEFAULT CHARACTER
SET utf8;

GRANT INSERT, CREATE, ALTER, UPDATE, SELECT, REFERENCES on cnc_iiot.*
TO "loudjein"@"%" IDENTIFIED BY 'secret1234'
WITH
GRANT OPTION;